name: CI

on:
  push:
    branches: ['5.0']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neo4j_version:
          - "4.4"
          - "5.1"
        neo4j_enterprise_edition:
          - "true"
          - "false"
        java_version:
          - 17
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: adopt
      - name: Cache ~/.m2/repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --batch-mode --show-version clean test
        env:
          NEO4J_VERSION: ${{ matrix.neo4j_version }}
          NEO4J_ENTERPRISE_EDITION: ${{ matrix.neo4j_enterprise_edition }}
